name: Generate HTML manual

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install packages
      # The mkdocs 'exclude' plugin is not available as Ubuntu package,
      # thus, install mkdocs and matching plugin via pip.
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        sudo pip install mkdocs mkdocs-exclude
    - name: Set git user name
      # This is purely for a nicer looking commit history
      run: git config --global user.name "EmuTOS documentation bot"
    - name: Build and deploy website
      # MkDocs 1.2, released on June 7th 2021, has a regression: it only pushes
      # HTML files to GitHub when called with the '--force' option.
      # https://github.com/mkdocs/mkdocs/commit/2688a6d88d61066268c19b51c835fcc1a8a9a43c
      run: |
        cd usermanual
        mkdocs gh-deploy --force
